# Generated by Django 3.0.2 on 2020-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='budget_id',
            field=models.IntegerField(blank=True, default=62305),
        ),
    ]
