# Generated by Django 3.0.2 on 2020-04-30 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200430_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listsitem',
            name='main_list',
        ),
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
