# Generated by Django 3.0.2 on 2020-05-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200501_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='balance',
        ),
    ]
