# Generated by Django 3.0.2 on 2020-05-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_list_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expence',
            name='excpence_id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_id',
        ),
        migrations.AlterField(
            model_name='listsitem',
            name='main_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.List'),
        ),
    ]
