# Generated by Django 3.0.2 on 2020-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_allowedmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedmembership',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
