# Generated by Django 3.0.2 on 2020-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200504_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'en'), ('Russian', 'ru'), ('Ukrainian', 'ua')], default='English', max_length=30),
        ),
    ]
