# Generated by Django 3.0.2 on 2020-05-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200504_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(default='English', max_length=40),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Languages'),
        ),
    ]
