# Generated by Django 3.0.2 on 2020-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200504_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
