# Generated by Django 3.0.2 on 2020-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_languages_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
